credentials:
  users:
    replicator:
      password: 'topsecret'
      roles: [ replication ]
    storage:
      password: 'secret'
      roles: [ sharding ]
    api:
      password: 'xxx'
      roles: [ super ]

iproto:
  advertise:
    peer:
      login: replicator
    sharding:
      login: storage

sharding:
  bucket_count: 1000

groups:
  user_storages:
    roles: [ roles.crud-storage ]
    app:
      module: user_storage
    sharding:
      roles: [ storage ]
    replication:
      failover: manual
    replicasets:
      user_storage-a:
        leader: user_storage-a-001
        instances:
          user_storage-a-001:
            iproto:
              listen:
              - uri: '127.0.0.1:3343'
              advertise:
                client: '127.0.0.1:3343'
          user_storage-a-002:
            iproto:
              listen:
              - uri: '127.0.0.1:3344'
              advertise:
                client: '127.0.0.1:3344'
          user_storage-a-003:
            iproto:
              listen:
              - uri: '127.0.0.1:3345'
              advertise:
                client: '127.0.0.1:3345'

      user_storage-b:
        leader: user_storage-b-001
        instances:
          user_storage-b-001:
            iproto:
              listen:
              - uri: '127.0.0.1:3346'
              advertise:
                client: '127.0.0.1:3346'
          user_storage-b-002:
            iproto:
              listen:
              - uri: '127.0.0.1:3347'
              advertise:
                client: '127.0.0.1:3347'
          user_storage-b-003:
            iproto:
              listen:
              - uri: '127.0.0.1:3348'
              advertise:
                client: '127.0.0.1:3348'
  user_routers:
    roles: [ roles.crud-router ]
    app:
      module: user_router
    sharding:
      roles: [ router ]
    replicasets:
      user_router-a:
        instances:
          user_router-a-001:
            iproto:
              listen:
              - uri: '127.0.0.1:3349'
              advertise:
                client: '127.0.0.1:3349'
