credentials:
  users:
    replicator:
      password: 'topsecret'
      roles: [ replication ]
    storage:
      password: 'secret'
      roles: [ sharding ]
    api:
      password: 'xxx'
      roles: [ super ]

iproto:
  advertise:
    peer:
      login: replicator
    sharding:
      login: storage

sharding:
  bucket_count: 4000

groups:
  data_storages:
    roles: [ roles.crud-storage ]
    app:
      module: data_storage
    sharding:
      roles: [ storage ]
    replication:
      failover: manual
    replicasets:
      data_storage-a:
        leader: data_storage-a-001
        instances:
          data_storage-a-001:
            iproto:
              listen:
              - uri: '127.0.0.1:3331'
              advertise:
                client: '127.0.0.1:3331'
          data_storage-a-002:
            iproto:
              listen:
              - uri: '127.0.0.1:3332'
              advertise:
                client: '127.0.0.1:3332'
          data_storage-a-003:
            iproto:
              listen:
              - uri: '127.0.0.1:3333'
              advertise:
                client: '127.0.0.1:3333'
      data_storage-b:
        leader: data_storage-b-001
        instances:
          data_storage-b-001:
            iproto:
              listen:
              - uri: '127.0.0.1:3334'
              advertise:
                client: '127.0.0.1:3334'
          data_storage-b-002:
            iproto:
              listen:
              - uri: '127.0.0.1:3335'
              advertise:
                client: '127.0.0.1:3335'
          data_storage-b-003:
            iproto:
              listen:
              - uri: '127.0.0.1:3336'
              advertise:
                client: '127.0.0.1:3336'
      data_storage-c:
        leader: data_storage-c-001
        instances:
          data_storage-c-001:
            iproto:
              listen:
              - uri: '127.0.0.1:3337'
              advertise:
                client: '127.0.0.1:3337'
          data_storage-c-002:
            iproto:
              listen:
              - uri: '127.0.0.1:3338'
              advertise:
                client: '127.0.0.1:3338'
          data_storage-c-003:
            iproto:
              listen:
              - uri: '127.0.0.1:3339'
              advertise:
                client: '127.0.0.1:3339'
      data_storage-d:
        leader: data_storage-d-001
        instances:
          data_storage-d-001:
            iproto:
              listen:
              - uri: '127.0.0.1:3340'
              advertise:
                client: '127.0.0.1:3340'
          data_storage-d-002:
            iproto:
              listen:
              - uri: '127.0.0.1:3341'
              advertise:
                client: '127.0.0.1:3341'
          data_storage-d-003:
            iproto:
              listen:
              - uri: '127.0.0.1:3342'
              advertise:
                client: '127.0.0.1:3342'
  data_routers:
    roles: [ roles.crud-router ]
    app:
      module: data_router
    sharding:
      roles: [ router ]
    replicasets:
      data_router-a:
        instances:
          data_router-a-001:
            iproto:
              listen:
              - uri: '127.0.0.1:3330'
              advertise:
                client: '127.0.0.1:3330'
